version: '3.7'

services:
    postgres:
        image: postgres:9.5.4
        container_name: "retraced.postgres"
        restart: unless-stopped
        ports:
            - "5434:5432"
        env_file:
            - env/common
            - env/postgres
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data

    migrate-postgres:
        build: ./
        container_name: "retraced.pg.migrate"
        working_dir: /src
        command:
          - /bin/sh
          - -c
          - make deps build && \
            node build/_db/runner-lite.js pg
        restart: on-failure
        env_file:
            - env/common
        volumes:
            - ./:/src
        depends_on:
            - postgres

    dashboard-postgres:
        image: ankane/pghero
        env_file:
            - env/common
        ports:
            - 5430:8080
        depends_on:
            - postgres
            - migrate-postgres

    migrate-elasticsearch:
        build: ./
        container_name: "retraced.es.migrate"
        working_dir: /src
        command:
        - /bin/sh
        - -c
        - make deps build && \
            node build/_db/runner-lite.js es
        restart: on-failure
        env_file:
            - env/common
        volumes:
            - ../api/migrations:/src/migrations
        depends_on:
            - postgres
            - elasticsearch

    redis:
        image: redis:3.2.3
        container_name: "retraced.redis"
        ports:
            - "6379:6379"
        restart: unless-stopped
        env_file:
            - env/common
            - env/redis

    nsqd:
        image: nsqio/nsq:v1.0.0-compat
        container_name: "retraced.nsqd"
        ports:
            - "4150:4150"
            - "4151:4151"
        restart: unless-stopped
        command: 
            - /nsqd
            - --statsd-address 
            - statsd:8125
        env_file:
            - env/common

    nsqadmin:
        image: nsqio/nsq:v1.0.0-compat
        container_name: "retraced.nsqadmin"
        ports:
            - "4171:4171"
        command: /nsqadmin --nsqd-http-address=nsqd:4151

    elasticsearch:
        image: elasticsearch:2.4.0
        container_name: "retraced.elasticsearch"
        ports:
            - "9200:9200"
        restart: unless-stopped
        env_file:
            - env/common
            - env/elasticsearch

    api:
        build:
            context: ../api/
            dockerfile: deploy/Dockerfile-slim
            target: node
            args:
                skip_pkg: 1
        container_name: "retraced.api"
        working_dir: /src
        volumes:
            - ../api:/src
        ports:
            - "3000:3000"
        env_file:
            - env/common
            - env/api
        command:
        - /bin/sh
        - -c
        - /usr/local/bin/node --no-deprecation build/index.js

    api-project-bootstrap:
        build:
            context: ../api/
            dockerfile: deploy/Dockerfile-slim
            target: node
            args:
                skip_pkg: 1
        container_name: "retraced.api-boostrap"
        working_dir: /src
        volumes:
            - ./:/src
        env_file:
            - env/common
            - env/api
            - env/api_project
        command:
          - /bin/sh
          - -c
          - /usr/local/bin/node --no-deprecation build/retracedctl.js bootstrap
    dbutil:
        build: ./
        container_name: "retraced.dbutil"
        working_dir: /src
        volumes:
            - ./:/src
        env_file:
            - env/common
        command: [sleep, infinity]

    mailcatcher:
        image: schickling/mailcatcher
        container_name: "retraced.mailcatcher"
        ports:
            - "1080:1080"
            - "1025:1025"

    processor:
        build:
            context: ../api/
            dockerfile: deploy/Dockerfile-slim
            target: node
            args:
                skip_pkg: 1
        container_name: "retraced.processor"
        working_dir: /src
        volumes:
            - ../api:/src
        env_file:
            - env/common
            - env/processor
        command: [make, build, run-processor]

    cron:
        build:
          context: ../api/
          dockerfile: deploy/Dockerfile-slim
          target: cron
        container_name: "retraced.cron"
        env_file:
            - env/common
            - env/processor
        command: 
          - /usr/local/bin/replicated-auditlog-cron
          - /crontab

    statsd:
        image: jaconel/statsd
        container_name: "retraced.statsd"
        restart: unless-stopped
        env_file:
            - env/statsd



