apiVersion: skaffold/v2beta27
kind: Config
build:
  local:
    push: false

  artifacts:
  - image: registry.replicated.com/library/retraced
    context: ./
    docker:
      dockerfile: ./Dockerfile.base

deploy:
  kustomize:
    paths:
    - ./kustomize/overlays/skaffold
