apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  selector:
    matchLabels:
      tier: cron
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: cron
        dest: nsq
        source: cron
    spec:
      containers:
        - name: cron
          image: registry.replicated.com/shipretraced/retraced:1.2.2
          command:
            - /bin/bash
            - -c
            - /usr/local/bin/replicated-auditlog-cron /crontab | grep ERRO
          env:
            - name: NSQD_HOST
              valueFrom:
                secretKeyRef:
                  name: nsq
                  key: NSQD_HOST
            - name: NSQD_HTTP_PORT
              valueFrom:
                secretKeyRef:
                  name: nsq
                  key: NSQD_HTTP_PORT
            - name: RETRACED_DISABLE_GEOSYNC
              value: "1"
      imagePullSecrets:
        - name: quayio
