apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-es-f5cd431
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    metadata:
      labels:
        app: retraced
        tier: db
        target: es
        type: migrate
        sha: "f5cd431"
    spec:
      imagePullSecrets:
        - name: quayio
      restartPolicy: Never
      containers:
        - name: db
          image: quay.io/retracedhq/db:f5cd431
          command:
            - bin/retraceddb
            - up
            - es
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DATABASE
            - name: ELASTICSEARCH_NODES
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_NODES
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: DB_TOKEN
            - name: BUGSNAG_STAGE
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: STAGE

