apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  selector:
    matchLabels:
      tier: processor
  replicas: 2
  template:
    metadata:
      labels:
        app: retraced
        tier: processor
    spec:
      volumes:
        - name: tmpdir
          emptyDir: {}
      containers:
        - name: processor
          image: registry.replicated.com/shipretraced/retraced:1.2.2
          command:
            - /src/processor
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
          env:
            - name: TMPDIR
              value: /tmp
            - name: NO_WARP_PIPE
              value: "1"
            - name: STATSD_HOST
              valueFrom:
                secretKeyRef:
                  name: statsd
                  key: HOST
            - name: STATSD_PORT
              valueFrom:
                secretKeyRef:
                  name: statsd
                  key: PORT
            - name: POSTGRES_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_POOL_SIZE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DATABASE
            - name: HMAC_SECRET_ADMIN
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_ADMIN
            - name: HMAC_SECRET_VIEWER
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET_VIEWER
            - name: RETRACED_APP_BASE
              value: ""
            - name: RETRACED_API_BASE
              valueFrom:
                secretKeyRef:
                  name: retraced
                  key: RETRACED_API_BASE
            - name: MANDRILL_KEY
              valueFrom:
                secretKeyRef:
                  name: mandrill
                  key: MANDRILL_KEY
            - name: ELASTICSEARCH_NODES
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_NODES
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: PROCESSOR_TOKEN
            - name: BUGSNAG_STAGE
              valueFrom:
                secretKeyRef:
                  name: bugsnag
                  key: STAGE
            - name: STATUSPAGEIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: statuspageio
                  key: token
            - name: NSQD_HOST
              value: "nsqd"
            - name: NSQD_TCP_PORT
              value: "4150"
            - name: NSQD_HTTP_PORT
              value: "4151"

      imagePullSecrets:
      - name: retraced-imagepull-secret

