apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-es
spec:
  template:
    spec:
      containers:
        - name: db
          image: retracedhq/retraced:1.5.3
          imagePullPolicy: IfNotPresent
