apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-api
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap
          image: retracedhq/retraced-local
      containers:
        - name: api
          image: retracedhq/retraced-local
          env:
            - name: PG_SEARCH
              value: ""
