apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  selector:
    matchLabels:
      tier: api
  replicas: 2
  template:
    metadata:
      labels:
        app: auditlog
        tier: api
    spec:
      imagePullSecrets:
        - name: auditlog-imagepull-secret
      containers:
        - name: api
          image: registry.replicated.com/shipretraced/retraced:1.2.2
          command:
            - /src/api
          ports:
            - containerPort: 3000
          env:
          - name: STATSD_HOST
            valueFrom:
              secretKeyRef:
                name: statsd
                key: HOST
          - name: STATSD_PORT
            valueFrom:
              secretKeyRef:
                name: statsd
                key: PORT
          - name: POSTGRES_POOL_SIZE
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_POOL_SIZE
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_HOST
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_PORT
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_DATABASE
          - name: HMAC_SECRET_ADMIN
            valueFrom:
              secretKeyRef:
                name: jwt
                key: HMAC_SECRET_ADMIN
          - name: HMAC_SECRET_VIEWER
            valueFrom:
              secretKeyRef:
                name: jwt
                key: HMAC_SECRET_VIEWER
          - name: RETRACED_APP_BASE
            valueFrom:
              secretKeyRef:
                name: auditlog
                key: RETRACED_APP_BASE
          - name: RETRACED_API_BASE
            valueFrom:
              secretKeyRef:
                name: auditlog
                key: RETRACED_API_BASE
          - name: RETRACED_API_SCHEMES
            valueFrom:
              secretKeyRef:
                name: auditlog
                key: RETRACED_API_SCHEMES
          - name: ELASTICSEARCH_NODES
            valueFrom:
              secretKeyRef:
                name: elasticsearch
                key: ELASTICSEARCH_NODES
          - name: AUTH0_CLIENT_DOMAIN
            valueFrom:
              secretKeyRef:
                name: auth0
                key: AUTH0_CLIENT_DOMAIN
          - name: AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth0
                key: AUTH0_CLIENT_ID
          - name: RETRACED_PUBLIC_SITE
            valueFrom:
              secretKeyRef:
                name: auditlog
                key: RETRACED_PUBLIC_SITE
          - name: BUGSNAG_TOKEN
            valueFrom:
              secretKeyRef:
                name: bugsnag
                key: API_TOKEN
          - name: BUGSNAG_STAGE
            valueFrom:
              secretKeyRef:
                name: bugsnag
                key: STAGE
          - name: NSQD_HOST
            valueFrom:
              secretKeyRef:
                name: nsq
                key: NSQD_HOST
          - name: NSQD_TCP_PORT
            valueFrom:
              secretKeyRef:
                name: nsq
                key: NSQD_TCP_PORT
          - name: NSQD_HTTP_PORT
            valueFrom:
              secretKeyRef:
                name: nsq
                key: NSQD_HTTP_PORT
