apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbutil
  labels:
    app: retraced
    tier: dbutil
spec:
  selector:
    matchLabels:
      app: retraced
      tier: dbutil
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: dbutil
    spec:
      volumes:
      - name: var-run
        hostPath:
          path: /var/run/retraced/
      imagePullSecrets:
      - name: quayio
      containers:
      - name: dbutil
        image: registry.replicated.com/shipretraced/retraced:1.3.1
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sleep
        - infinity
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/run/retraced/
          name: var-run
          readOnly: true
        envFrom:
          - secretRef:
              name: auditlog
