apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-pg-1-3-1
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db
        image: registry.replicated.com/shipretraced/retraced:1.3.1
        imagePullPolicy: IfNotPresent
        command:
        - /src/retraceddb
        - up
        - pg
        envFrom:
        - secretRef:
            name: auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: auditlog
              key: DB_TOKEN
      imagePullSecrets:
      - name: auditlog-imagepull-secret
