apiVersion: v1
kind: Pod
metadata:
  name: integrationtest
spec:
  restartPolicy: OnFailure
  containers:
    - name: tests
      image: registry.replicated.com/shipretraced/retraced:1.3.1
      command:
        - npx
        - mocha
        - -r
        - ts-node/register
        - integration/test/**/*.ts
