apiVersion: apps/v1
kind: Pod
metadata:
  name: integrationtest
spec:
  containers:
    - name: tests
      image: registry.replicated.com/shipretraced/retraced:1.3.1
      imagePullPolicy: IfNotPresent
      command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/index.ts
      ports:
      - containerPort: 9229
